# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('place', models.TextField(max_length=500, verbose_name='Lugar')),
                ('event_date', models.DateTimeField(verbose_name='Fecha y hora')),
                ('duration', models.CharField(blank=True, max_length=200, null=True, verbose_name='Duraci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEstudiantil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='grupo_estudiantil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gem.GrupoEstudiantil'),
        ),
    ]
