# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gem.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_name', models.CharField(max_length=200)),
                ('usuario_apellido_paterno', models.CharField(max_length=200)),
                ('usuario_apellido_materno', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='asistencia',
            name='usuario_asistente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gem.Usuario'),
        ),
    ]
