# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0003_grupoestudiantil_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoestudiantil',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
