# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0004_grupoestudiantil_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoestudiantil',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
